### ISSUE TITLE
radikoが聴取できません。

### ISSUE THREAD

**Issue by hiro0312** [Angelmaneuver/pirate-radio#1]
お世話になります。
Xでの返信をありがとうございました。

要件は「radiko」を受信・聴取できないということです。
ダウンロードさせて頂き、ここ一週間ほど格闘しましたが
どうやっても聴取できないので、作者様にご教示をお願いしたく
連絡させて頂いた次第です。

(1)ハードウェア
Pimoroni Pirate Radio(Raspberri Pi Zero W)

(2)OS
2020-02-13-raspbian-buster-lite

(3)依存関係のあるモジュール。
pip list
Package            Version
------------------ ---------
asn1crypto         0.24.0
beautifulsoup4     4.7.1
certifi            2018.8.24
cffi               1.15.1
chardet            3.0.4
charset-normalizer 3.3.2
click              8.1.7
cryptography       3.3
entrypoints        0.3
Flask              2.2.5	<---Flask
html5lib           1.0.1
idna               2.6
importlib-metadata 6.7.0
isodate            0.6.1
itsdangerous       2.1.2
Jinja2             3.1.3
keyring            17.1.1
keyrings.alt       3.1.1
lxml               4.3.2
MarkupSafe         2.1.5
parse              1.6.5
phatbeat           0.1.1
pip                24.0
pycountry          22.3.5
pycparser          2.21
pycrypto           2.6.1
pycryptodome       3.20.0
PyGObject          3.30.4
pyparser           1.0
pyparsing          2.1.0
PySocks            1.7.1
python-apt         1.8.4.3
pyxdg              0.25
requests           2.31.0
RPi.GPIO           0.7.0
SecretStorage      2.3.1
setuptools         68.0.0
six                1.12.0
soupsieve          1.8
ssh-import-id      5.7
streamlink         5.5.1	<---streamlink
typing_extensions  4.7.1
urllib3            2.0.7
webencodings       0.5.1
websocket-client   1.6.1
Werkzeug           2.2.3
wheel              0.32.3
zipp               3.15.0

デフォルトpython v3.7.3
(OSインストール直後のデフォルトPythonは v2.7.16 でしたが、
receiverdの実行時にdef構文の所でシンタックス・エラーが出たため
現在は v3.7.3 をデフォルトとしております。）

VLC media player 3.0.20 Vetinari (revision 3.0.20-0-g6f0d0ab126b)

(4)vlcのログ/run/vlcd/vlcd.logの内容は以下の通りです。
-- logger module started --
lua: Lua HTTP interface
main error: no suitable interface module
main error: interface "globalhotkeys,none" initialization failed
lua: Listening on host "0.0.0.0:9294".
dummy: using the dummy interface module...
access error: HTTP connection failure
main error: connection failed: Connection refused
main error: connection failed: Connection refused
http error: cannot connect to localhost:8888
main error: Your input can't be opened
main error: VLC is unable to open the MRL 'http://localhost:8888/radiko?sid=TBS'. Check the log for details.

(5)ps auxコマンドで起動しているタスクを見ますと、
phatbeatd と vlc はありますが、 /usr/bin/receiverd はありません。

root       553  0.0  1.6  47308  7208 ?        Sl   00:18   0:00 python /usr/bin/phatbeatd
pi         735  0.1  2.8 332760 12660 pts/0    Tl   00:21   0:00 vlc
この状態で curl -i localhost:8888/ で以下のエラーです。
pi@raspberrypi:~ $ curl -i localhost:8888/
curl: (7) Failed to connect to localhost port 8888: Connection refused

手動で /usr/bin/received を起動しますと以下のようになります。
pi@raspberrypi:~ $ curl -i localhost:8888/
curl: (7) Failed to connect to localhost port 8888: Connection refused

pi@raspberrypi:~ $ python3 /usr/bin/receiverd
 * Serving Flask app 'receiverd'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8888
 * Running on http://192.168.1.11:8888
Press CTRL+C to quit

pi@raspberrypi:~ $ curl -i localhost:8888/
HTTP/1.1 500 INTERNAL SERVER ERROR
Server: Werkzeug/2.2.3 Python/3.7.3
Date: Wed, 03 Apr 2024 23:35:11 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 265
Connection: close

<!doctype html>
<html lang=en>
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

この時の vlc のログは以下となります。
sudo nano /run/vlcd/vlcd.log

-- logger module started --
lua: Lua HTTP interface
main error: no suitable interface module
main error: interface "globalhotkeys,none" initialization failed
lua: Listening on host "0.0.0.0:9294".
dummy: using the dummy interface module...
access error: HTTP connection failure
main error: connection failed: Connection refused
main error: connection failed: Connection refused
http error: cannot connect to localhost:8888
main error: Your input can't be opened
main error: VLC is unable to open the MRL 'http://localhost:8888/radiko?sid=TBS'. Check the log for details.

(6)また貴殿の pirate radio インストール時のサービス登録では以下のメッセージが出ます。
receiverd.service is not a native service, redirecting to systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable receiverd

ですが起動しているサービスを確認しますと登録はされているようです。
pi@raspberrypi:~ $ systemctl list-unit-files

phatbeatd.service                      generated
receiverd.service                      generated
vlcd.service                           generated

(7)尚、receiverdの中のrediko.jpのURLでは「!」の前に「\」を書き足してradikoの現状に合わせてあります。

'https://radiko.jp/!/live/{0}' ---> 'https://radiko.jp/#!/live/{0}'

以上がこちらの状況です。
何かアップデートやアドバイス等ありましたらご教示頂ければ幸いです。

どうぞよろしくお願い致します。

何としても pirate radio で　radiko を聴きたいのです。

**Comment by Angelmaneuver** [comment]
## まず始めに
このアプリケーションの概要を説明します。

このアプリケーションは Pirate Radio – Pi Zero WH Project Kit (以降、キットと記載) で Radiko の放送が聞けるようにしたものです。元々のキットは VLC を介してネットストリーミングをスピーカーに流すというものでした。

が、Radiko は VLC で再生できません。そこで Radiko のストリーミングを Streamlink と呼ばれるライブラリを使用してストリーミングデータを取得し、Flask と呼ばれる Web フレームワークで HTTP ストリーミングを公開することで VLC が再生できるようにしたものです。

スピーカー -> VLC -> receiverd (Flask Web) -> receiverd (Streamlink) -> Radiko

## それを踏まえた上で
まず、hiro0312 さんの下記対応が問題で receiverd (Flask Web) が正常に動作してないと思います。
```
(7)尚、receiverdの中のrediko.jpのURLでは「!」の前に「\」を書き足してradikoの現状に合わせてあります。

'[https://radiko.jp/!/live/{0}](https://radiko.jp/!/live/%7B0%7D)' ---> '[https://radiko.jp/#!/live/{0}](https://radiko.jp/#!/live/%7B0%7D)'
```
私は今もテレワークの友として Pirate Radio で Radiko の放送を流していますが、上記対応をする事なくリポジトリのソースのままで問題なく聞けています (正に今この時も流れています)。

ソースを修正前の状態に戻し、下記コマンド (開発機でやったので Raspberry pi ではもしかしたら変えないとダメかもしれません) で receiverd (Flask Web) が正常に起動するか確認してください。
```
python receiverd.py -d
```
-d (デバッグモード) で起動すると Webブラウザから下記 URL にアクセスする事で Radiko の放送を聞くことができます。
```
http://pirate-radio の IP アドレス:8888/radiko?sid=FMT
```
放送が流れたら receiverd (Flask Web)・receiverd (Streamlink) が問題なく動作していますので、それでも流れない場合はキットの設定 ? か、VLC の問題 ? となります。

## この issue は
特に追加の質問等がなかった場合は、1 週間程度でクローズとなります。

**Comment by hiro0312** [comment]
返信ありがとうございました。

receiverdの内容を元に戻して、ブラウザから http://192.168.1.11:8888/radiko?sid=FMT にアクセスしてみましたが、
放送は流れずに下記のエラーが出ます。

InternalServerError

werkzeug.exceptions.InternalServerError: 500 Internal Server Error: Exception NameError: name 'streamlink' is not defined

Traceback (most recent call last)

    File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request

    rv = self.dispatch_request()

    File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request

    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)

    File "/home/pi/Pimoroni/phatbeat/projects/vlc-radio/receiverd.py", line 34, in radiko

    streams = streamlink().streams(

During handling of the above exception, another exception occurred:
    File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 2552, in __call__

    return self.wsgi_app(environ, start_response)

    File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 2532, in wsgi_app

    response = self.handle_exception(e)

    File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app

    response = self.full_dispatch_request()

    File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request

    rv = self.handle_user_exception(e)

    File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 1676, in handle_user_exception

    return self.ensure_sync(handler)(e)

    File "/home/pi/Pimoroni/phatbeat/projects/vlc-radio/receiverd.py", line 48, in error

    EXCEPTION_MESSAGE.format(type(error).__name__, error),

    File "/home/pi/.local/lib/python3.7/site-packages/flask/helpers.py", line 310, in abort

    current_app.aborter(code, *args, **kwargs)

    File "/home/pi/.local/lib/python3.7/site-packages/werkzeug/exceptions.py", line 864, in __call__

    raise self.mapping[code](*args, **kwargs)

werkzeug.exceptions.InternalServerError: 500 Internal Server Error: Exception NameError: name 'streamlink' is not defined


何やらStreamlinkがまずいのでしょうか？？？
どうぞよろしくお願い致します。

**Comment by hiro0312** [comment]
お世話になります。

ブラウザのエラーの原因はFirefoxに起因するものでした。
Chromeで http://192.168.1.11:8888/radiko?sid=FMT にアクセスしましたら放送を聴くことができました。

ですが、receiverd はデバッグモードでないと聴けません。
" -d" を外して python receiverd.py でやるとブラウザでは文字列としてダウンロードされてしまいます。

この後はどのようにすれば良いでしょうか？？？

どうぞよろしくお願い致します。

**Comment by Angelmaneuver** [comment]
デバッグモードは receiverd の動作確認用です。
Pirate Radio – Pi Zero WH Project Kit で動作させようとすると、Web ブラウザからは文字化けした文字列が列挙されるようになるので正常に動作しています。

その為、このアプリケーションは正常に動作しているという事になるので後は Pirate Radio – Pi Zero WH Project Kit か、VLC の設定が問題という事になります。

確認するべき点としては

 - Pirate Radio – Pi Zero WH Project Kit のスピーカーが正常に動作しているか (スピーカーから音が流れたことがあるか)
 - VLC がエラーとなっていないか (エラーとなっている場合は、そのログから問題点を見つけて解消するしかない)

ぐらいでしょうか。

いずれにしても後は実機を手探りで試してもらうしかありません。

**Comment by hiro0312** [comment]
お世話になります。

(1)default.m3uの局リストを以下にして、Pirate Radio – Pi Zero WH Project Kit の電源を入れますと・・・
---------------------------------------------------------------------
#EXTM3U

#EXTINF:-1,SlayRadio
http://relay4.slayradio.org:8200/

#EXTINF:-1,TBSラジオ
http://localhost:8888/radiko?sid=TBS
---------------------------------------------------------------------
1局目のSlayRadioは再生されて音声が出力されますが2曲目のTBS(radiko)は音声が出ません。
またこの状態でkit本体から再生ボタンを押して一旦ストップさせた状態で
ブラウザから http://192.168.1.11:8888/radiko?sid=TBS にアクセスしますと、
ブラウザ画面には文字化けした文字列が列挙されずに以下のエラーがブラウザ画面に出ます。
---------------------------------------------------------------------
503 Service Unavailable
---------------------------------------------------------------------
receiverdサービスが起動していないように見えます。
この時の vlc のログは以下です。
------------------------------------------------------------------------------------------------------------------
-- logger module started --
lua: Lua HTTP interface
main error: no suitable interface module
main error: interface "globalhotkeys,none" initialization failed
lua: Listening on host "0.0.0.0:9294".
dummy: using the dummy interface module...
http warning: ICY metaint=8192
mpeg4audio: AAC channels: 1 samplerate: 16000
faad warning: decoded zero sample
pulse warning: starting late (-25249 us)
access error: HTTP connection failure
http error: cannot connect to allstream.rainwave.cc:8000
access error: HTTP connection failure
main error: connection failed: Connection refused
main error: connection failed: Connection refused
http error: cannot connect to localhost:8888
main error: Your input can't be opened
main error: VLC is unable to open the MRL 'http://localhost:8888/radiko?sid=TBS'. Check the log for details.
------------------------------------------------------------------------------------------------------------------

(2)次に receiverd をデバッグモードで起動 ( python receiverd.py -d )して kit の再生ボタンを押すと、
以下のようにデバッグモードの receiverd にGET要求は通っているようですが音声は出ません。
------------------------------------------------------------------------------------------------------------------
pi@raspberrypi:~/Pimoroni/phatbeat/projects/vlc-radio $ python receiverd.py -d
 * Serving Flask app 'receiverd'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8888
 * Running on http://192.168.1.11:8888
Press CTRL+C to quit
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 126-535-178
127.0.0.1 - - [05/Apr/2024 21:38:05] "GET /radiko?sid=TBS HTTP/1.1" 200 -
------------------------------------------------------------------------------------------------------------------

このような状態で何が推測されるでしょうか？？？

どうぞよろしくお願い致します。

**Comment by Angelmaneuver** [comment]
推測も何も、もう答えが出てるように見えますが…

> receiverdサービスが起動していないように見えます。

> (2)次に receiverd をデバッグモードで起動

先述しているようにデバッグモードは receiverd の動作確認用です。
Pirate Radio – Pi Zero WH Project Kit で動作させることができません

receiverd をデバッグモードで起動せず (-d オプションを付けない) 、普通に起動した上で VLC から再生させないと確認になってません。

**Comment by hiro0312** [comment]
お世話になります。

receiverd を普通に起動したらTBSも聴くことができました、ありがとうございます。

そこで receiverd をサービスに登録して自動で起動するにはどうすれば良いのか教えてください。

どうぞよろしくお願い致します。

**Comment by Angelmaneuver** [comment]
申し訳ないですけど、それは hiro0312 さんで調べてみてください。
setup.sh の登録が失敗してると思うのでログから原因を切り出してサービス登録してみてください。

2 年前にやったので私も覚えてないので、エラー内容を Google 検索した方が早いと思います。

**Comment by hiro0312** [comment]
お世話になっております。

お陰様で receiverd.py の自動起動に成功して radiko を聴取できております。

原因は /etc/init.d/receiverd 内の記述 PATH=/sbin:/usr/sbin:/bin:/usr/bin にありました。
当方は Flask、Streamlink 共に ユーザ環境でのみ動作するようにインストールしてあったので、
PATH に /home/pi/.local/bin: を追記する必要がありました。
この記述が足りなかったが故にサービス登録されているにも関わらず receiverd が receiverd.py を起動できなかったようです。

玖堂恵 様には、ど素人の私をここまで導いて下さって感謝しております、ありがとうございました。

現状、radiko の聴取には満足しておりますが、電源投入から再生音声の出力に5分掛かること
(これはサービスに TimeoutSec=5min と設定されているからだと思います) と Vu-Meter が振れないという問題点があります。
しかしながらこの点は今後調査して解決していこうと考えております。

この度は大変お世話になりました。
もう一度、ありがとうございました。
