### ISSUE TITLE
Couldn't install this repository

### ISSUE THREAD

**Issue by todopapa** [Angelmaneuver/pirate-radio#2]
Could you tell me how to install this repository to  current Pirate Radio install ?

**Comment by Angelmaneuver** [comment]
Hi todopapa.
I'll answer for your issue.

Sorry, this repository's installation script is over 2 years old and most likely does not work now.
You try to deal with it yourself, referring to #1 .
If you can't do that, then give up.

If there are no additional questions, I'll close this issue in about week.

**Comment by todopapa** [comment]
Thank you for the rapid reply.
早速の回答を有難うございました。
I'd like to check similar issue on #1, and try to install this way.
Anyway, thank you for your support.
updateもあって難しそうですね、無理そうなら早めに撤退して、別の方法でRani Musicが聴けるようにしたいと思います。サポートありがとうございました。
